networks:
  freshmart-net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: fm_zookeeper
    networks:
      - freshmart-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: fm_kafka
    networks:
      - freshmart-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fm_kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  freshmart-app:
    build: .
    container_name: fm_app
    networks:
      - freshmart-net
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - KAFKA_BOOTSTRAP=fm_kafka:9092
      - PYSPARK_PYTHON=python
      - PYSPARK_DRIVER_PYTHON=python
    depends_on:
      - kafka
    command: tail -f /dev/null
